on:
  push:
    tags:
      - 'v*.*.*'
name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set env
        run: echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV
      - name: Build
        run: docker build -t  ghcr.io/avi-kubiya/mermaidserver:latest -t  ghcr.io/avi-kubiya/mermaidserver:${{ env.RELEASE_VERSION }} -f Dockerfile .
      - name: Login
        run: echo ${{ secrets.GHCR_GITHUB_TOKEN }} | docker login -u avi.rosenberg@kubiya.ai --password-stdin
      - name: Push
        run:  ghcr.io/avi-kubiya/mermaidserver:latest && docker push  ghcr.io/avi-kubiya/mermaidserver:${{ env.RELEASE_VERSION }}